openapi: 3.0.3
info:
  title: Customer Accounts
  description: REST service for managing customer accounts.
  version: "1.0"
servers:
- url: /api
tags:
- name: Accounts
  description: Operations that apply to the collection of customer accounts.
- name: Account
  description: Operations that apply to a single customer account.
paths:
  /accounts:
    get:
      tags:
      - Accounts
      summary: Get customer accounts.
      description: Get the complete details for all accounts.
      operationId: get accounts
      responses:
        200:
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      tags:
      - Accounts
      summary: Create a new customer account.
      description: Create a new customer account.
      operationId: create account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        201:
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        422:
          description: <b>Not created.</b> Customer account with that ID already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /accounts/account/{id}:
    parameters:
    - name: id
      in: path
      description: The customer's account ID.
      required: true
      schema:
        type: string
    put:
      tags:
      - Account
      summary: Replace a customer account.
      description: Replace an existing customer account with a new version.
      operationId: update customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        200:
          description: Updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          description: <b>Not updated.</b> Customer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        409:
          description: <b>Not updated.</b> Changing a customer's account ID address
            is not permitted via this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      tags:
      - Account
      summary: Delete a customer account.
      description: Delete an existing customer account.
      operationId: delete account
      responses:
        204:
          description: Deleted.
        404:
          description: <b>Not deleted.</b> Customer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    Account:
      required:
      - email
      - firstName
      - lastName
      - username
      type: object
      properties:
        id:
          type: string
          description: Server generated.
        email:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        group:
          type: string
          description: Server generated.
    ErrorMessage:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: A message describing the error.
